### ISSUE TITLE
Removal of peerDependencies

### ISSUE THREAD

**Issue by samrocksc** [corpix/material-ui-upload#2]
# Issue
React and material-ui are beasts of many versions....by utilizing peerDependencies the actual use case of this module(which is fantastic) is cut into a small subset.

# Recommendation
Removal of peerDependencies and simply switching them to the dependency tree.

**Comment by dmoskovtsov** [comment]
+1

**Comment by corpix** [comment]
Removed peer deps in https://github.com/corpix/material-ui-upload/commit/0f070105ebff45b0a9786e34cdf5f3761c929e61
