### ISSUE TITLE
Cannot import material-ui-upload to React (Webpack)

### ISSUE THREAD

**Issue by developerPratik** [corpix/material-ui-upload#5]
I installed the module using npm. I also noticed that the index.js file is missing from the module's root directory, could that be the issue?

**Comment by corpix** [comment]
What was the actual error and your code?
Everything works for me in react project using the example https://github.com/corpix/material-ui-upload#usage-example

**Comment by corpix** [comment]
Little update: I have listed all components in autogenerated index.js file. It will not exist under version control but will exist in the npm package. Made this decision because this module contains two components(Upload, UploadPreview), so index.js will export a hashmap of this to components.

**Comment by corpix** [comment]
Closing this, feel free to open if problem persists.
