### ISSUE TITLE
Input is visible. How to solve it?

### ISSUE THREAD

**Issue by pacozaa** [corpix/material-ui-upload#6]
![capture](https://user-images.githubusercontent.com/3154089/27815034-4b26c2f4-60ab-11e7-8118-a3c544ef9947.JPG)

Any idea how make it looks like yours?

**Comment by corpix** [comment]
Do you use CSS modules? I have a [CSS](https://github.com/corpix/material-ui-upload/blob/afdd5ae9152277e84541fb452f0872c25ce6e9e8/src/Upload/index.css#L7) for the [file input field](https://github.com/corpix/material-ui-upload/blob/e184df0685a3ea7a272f973c2bc96bb1a0cfdaf9/src/Upload/index.js#L86).

CSS modules is the [essintial requirement](https://github.com/corpix/material-ui-upload#requirements) for this module to work.

**Comment by corpix** [comment]
Closing this, feel free to reopen if problem persists
