### ISSUE TITLE
Way to use RaisedButton?

### ISSUE THREAD

**Issue by dennervidal** [corpix/material-ui-upload#7]
Hi, there is a way to use RaisedButton?

**Comment by corpix** [comment]
At this moment you can't, but I think I can make a prop which could be used to define a component constructor to use as a button.

**Comment by dennervidal** [comment]
That would be great!
Thanks man

**Comment by corpix** [comment]
Published 1.1.6 with `buttonControl` [prop](https://github.com/corpix/material-ui-upload#upload-2).
Usage [example](https://github.com/corpix/material-ui-upload/blob/a4b692ac33aedaea41d3aba9ccc551c5e8a6a43c/stories/index.js#L38)
