### ISSUE TITLE
Image preview doesn't show up on second loading

### ISSUE THREAD

**Issue by geohuz** [corpix/material-ui-upload#8]
Load an image file, remove it, and load it again, the image preview doesn't show any image preview. But it does after loading another file then load the previous file again

**Comment by corpix** [comment]
I have reproduced this. Probably I have screwed it up while refactoring, will fix this soon. Thank you!

**Comment by corpix** [comment]
Upload component is not re-rendering, so it already has last «uploaded» image as the value.
https://github.com/corpix/material-ui-upload/commit/54d1cab58d2c68fe041a2387f29c968591c5d6e2 (included in version 1.2.1) should fix this. But I am concerned about how ugly this solution is and will leave this issue open for some time, probably some people could contribute more beautiful solution.

**Comment by corpix** [comment]
Will fix this in #10
